### ISSUE TITLE
[Services] MWRpy

### ISSUE THREAD

**Issue by tobiasmarke** [ACTRIS-Data-Centre/dvas-catalog#15]
## New service metadata: 
{
"title": "MWRpy - Microwave Radiometer data processing",
"url": "https://github.com/actris-cloudnet/mwrpy",
"description": "MWRpy is a standalone Python package for Microwave Radiometer (MWR) data processing. It is implemented in the ACTRIS Cloud Remote Sensing (CRS) data centre unit CLU, and used in the production chain of the cloud classification algorithm Cloudnet.",
"keywords": ["CLU", "Python", "Cloudnet", "Data", "Processing", "MWRpy", "Microwave Radiometer", "Remote Sensing"],
"img_url": "",
"access_rights": "Open",
"class": "Software"
}

Permitted values for some elements: 
access_rights: Open, Restricted 
class: Service, Tool, Product, Document

![mwrpy](https://github.com/user-attachments/assets/6db5f8d8-8648-4ebd-8e7b-74e72d225c10)

**Comment by richard-olav** [comment]
The service is included in the services file and will soon be visible in the DVAS portal. https://github.com/ACTRIS-Data-Centre/dvas-catalog/commit/e22cccdfa56d24c1cf51c565de07834f914e4601

**Comment by tobiasmarke** [comment]
Thanks! Would it be possible to change the "access_rights" to "Open" only and the "class" to "Software" so that the service ends up in the correct tab in the portal?

**Comment by richard-olav** [comment]
@tobiasmarke I have now updated the services file according to the suggested changes above. Thank you for providing the metadata.
