### ISSUE TITLE
API to update existing metadata records

### ISSUE THREAD

**Issue by siiptuo** [ACTRIS-Data-Centre/dvas-catalog#17]
Now you have DELETE record and recreate it with new ID. It would be nice to be able to update existing record and keep the same ID.

**Comment by richard-olav** [comment]
You can now use the /metadata/add endpoint for updating. The endpoint adds or updates a single metadata document. If a document with a given PID already exists it is overwritten with the new metadata, if not it is added as a new metadata record.

You can test using: https://dev-actris-md2.nilu.no/

New version of the api in production can be found here: https://prod-actris-md2.nilu.no/
