### ISSUE TITLE
Clarify software metadata field

### ISSUE THREAD

**Issue by siiptuo** [ACTRIS-Data-Centre/dvas-catalog#18]
What should be included in the software field? Currently it seems that it should be a single URI? Should it link to a source code repository, DOI or documentation? Also, how to include multiple software?

**Comment by lisemurberg** [comment]
Good question! 

Ideally each software should get a PID and this should be the link. By following the PID the user should be able to access source code and documentation. If the software does not have a PID, we should discuss how it can be referenced best.

Inclusion on multiple software should be part of the metadata upgrade @richard-olav.

**Comment by richard-olav** [comment]
This has not been discussed in detail. The initial idea was a URI to a landing-page with documentation describing the software or a list of processing routines and softwares/procedures being used. There is a separate convention for provenance metadata PROV-O that has been considered in the past.

I don't think a list of links to software is appropriate for the user unless we also expand the schema to include more provenance metadata (PROV-O).

I will transfer this to the internal list at NILU. For now I would link to the documentation of the processing routines and software. For ACTRIS In Situ we link to the repo containing a wiki.
