### ISSUE TITLE
Bad request if several files in basket

### ISSUE THREAD

**Issue by tukiains** [ACTRIS-Data-Centre/dvas-catalog#4]
If you add several files, e.g. 20 Cloudnet files, to the DVAS basket, and try to open it, the portal responds with 400 and error message: `Your browser sent a request that this server could not understand. Size of a request header field exceeds server limit.` After this, the site can be used only after deleting cookies.

**Comment by richard-olav** [comment]
Yes. Thank you for the feedback. The issue has been with generating cookies client side and releasing new versions of the dev-portal. Hopefully it will be less major changes in the future.
